version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: ddaas
      TZ: Europe/Warsaw
    ports:
      - "5432:5432"
    networks:
      - my-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: iot-anomaly-detection
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/ddaas
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
      TZ: Europe/Warsaw

    depends_on:
      - postgres
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
