apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  application.properties: |
    spring.datasource.url=jdbc:postgresql://host.docker.internal:5432/ddaas
    spring.datasource.username=postgres
    spring.datasource.password=1234
