apiVersion: v1
kind: Service
metadata:
  name: iot-anomaly-detection
spec:
  selector:
    app: iot-anomaly-detection
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer

