-- Tworzenie schematu 'test_schema', jesli nie istnieje
CREATE SCHEMA IF NOT EXISTS test_schema;

-- Tworzenie tabeli 'iotdata' w schemacie 'test_schema' (zawiera dane z czujnikow)
-- Jesli tabela juz istnieje, nie bedzie tworzona ponownie
CREATE TABLE IF NOT EXISTS test_schema.iotdata (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id VARCHAR(255),
    last_read TIMESTAMP,
    sensor1 INTEGER,
    sensor2 INTEGER,
    temperature_sensor REAL,
    timestamp TIMESTAMP,
    user_id BIGINT
);

-- Tworzenie tabeli 'anomaly' w schemacie 'test_schema' (zawiera informacje o anomaliach)
-- Jesli tabela juz istnieje, nie bedzie tworzona ponownie
CREATE TABLE IF NOT EXISTS test_schema.anomaly (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id VARCHAR(255),
    timestamp TIMESTAMP,
    type VARCHAR(255),
    user_id BIGINT,
    wartosc INTEGER
);

-- Tworzenie tabeli 'user' w schemacie 'test_schema' (zawiera dane użytkownikow)
-- Jesli tabela juz istnieje, nie bedzie tworzona ponownie
CREATE TABLE IF NOT EXISTS test_schema.user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255),
    password VARCHAR(255),
    username VARCHAR(255),
    role VARCHAR(255)
);