CREATE SCHEMA IF NOT EXISTS test_schema;

CREATE TABLE IF NOT EXISTS test_schema.iotdata (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id VARCHAR(255),
    last_read TIMESTAMP,
    sensor1 INTEGER,
    sensor2 INTEGER,
    temperature_sensor REAL,
    timestamp TIMESTAMP,
    user_id BIGINT
);

CREATE TABLE IF NOT EXISTS test_schema.anomaly (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id VARCHAR(255),
    timestamp TIMESTAMP,
    type VARCHAR(255),
    user_id BIGINT,
    wartosc INTEGER
);